/** The compiler's repository, as `owner/name`: the form the API takes. */
export const REPO_SLUG = 'lab-lang/lab'

export const REPO_URL = `https://github.com/${REPO_SLUG}`

/**
 * Where the site is served. Canonical links and social card URLs have to be
 * absolute, so a crawler resolving them has nothing relative to fall back on.
 */
export const SITE_ORIGIN = 'https://www.lab-compiler.org'

export const SITE_NAME = 'Lab'

/**
 * The install card is held back while the Python package is being finished:
 * it prints commands that do not resolve yet, and an install line a visitor
 * pastes into a terminal is the worst place on the site to be aspirational.
 * Set to `true` to bring it back on the homepage, in the hero and in the
 * phone-width closing note both.
 */
export const SHOW_INSTALL_COMMAND = false

/** The card image every route shares, generated by `scripts/og-images.py`. */
export const SOCIAL_IMAGE = '/og/lab.png'

export const DEFAULT_TITLE = 'The Lab Compiler'

export const DEFAULT_DESCRIPTION =
  'The Lab compiler turns experiments described in Lab or Python into LAIR, one verified intermediate representation, and from LAIR into work a laboratory can run.'

/** Every route but the homepage names itself ahead of the site. */
export function pageTitle(page: string) {
  return `${page} — ${DEFAULT_TITLE}`
}
