export const REPO_URL = 'https://github.com/lab-lang/lab'

/**
 * Where the site is served. Canonical links and social card URLs have to be
 * absolute, so a crawler resolving them has nothing relative to fall back on.
 */
export const SITE_ORIGIN = 'https://lab-lang.org'

export const SITE_NAME = 'Lab'

/** The card image every route shares, generated by `scripts/og-images.py`. */
export const SOCIAL_IMAGE = '/og/lab.png'

export const DEFAULT_TITLE = 'Lab — a programming language for biology'

export const DEFAULT_DESCRIPTION =
  'Lab is a programming language and compiler toolchain for describing biology and orchestrating work in the laboratory.'
