#!/usr/bin/env bash
#
# Builds crates/lab-ide-wasm from the sibling `lab` checkout and vendors the
# browser-ready bundle into src/wasm/lab-ide-wasm/. The output is committed
# to git: there is no Rust toolchain at deploy time, so this script is run
# by hand whenever lab-ide-wasm (or its lab-ide/lab-language dependencies)
# changes, and the result is checked in like any other generated asset.
set -euo pipefail

WEBSITE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAB_REPO="${LAB_REPO:-"$WEBSITE_ROOT/../lab"}"
OUT_DIR="$WEBSITE_ROOT/src/wasm/lab-ide-wasm"
PINNED_WASM_BINDGEN="0.2.126"

if [[ ! -f "$LAB_REPO/crates/lab-ide-wasm/Cargo.toml" ]]; then
  echo "error: LAB_REPO ($LAB_REPO) does not look like the lab workspace" >&2
  echo "       set LAB_REPO=/path/to/lab to point at your checkout" >&2
  exit 1
fi

if ! command -v wasm-bindgen >/dev/null 2>&1; then
  echo "error: wasm-bindgen CLI not found" >&2
  echo "       install it with: cargo install wasm-bindgen-cli --version $PINNED_WASM_BINDGEN --locked" >&2
  exit 1
fi

CRATE_WASM_BINDGEN="$(grep -A1 '^name = "wasm-bindgen"$' "$LAB_REPO/Cargo.lock" | grep '^version' | head -1 | cut -d'"' -f2)"
CLI_WASM_BINDGEN="$(wasm-bindgen --version | awk '{print $2}')"

if [[ "$CRATE_WASM_BINDGEN" != "$CLI_WASM_BINDGEN" ]]; then
  echo "error: wasm-bindgen CLI version ($CLI_WASM_BINDGEN) does not match" >&2
  echo "       the wasm-bindgen crate pinned in Cargo.lock ($CRATE_WASM_BINDGEN)" >&2
  echo "       reinstall with: cargo install wasm-bindgen-cli --version $CRATE_WASM_BINDGEN --locked" >&2
  exit 1
fi

if ! rustup target list --installed | grep -q '^wasm32-unknown-unknown$'; then
  echo "error: wasm32-unknown-unknown target not installed" >&2
  echo "       install it with: rustup target add wasm32-unknown-unknown" >&2
  exit 1
fi

echo "==> building lab-ide-wasm ($LAB_REPO)"
cargo build --release --target wasm32-unknown-unknown \
  --manifest-path "$LAB_REPO/Cargo.toml" \
  -p lab-ide-wasm

WASM_INPUT="$LAB_REPO/target/wasm32-unknown-unknown/release/lab_ide_wasm.wasm"

echo "==> emitting browser bindings to $OUT_DIR"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
wasm-bindgen --target web --out-dir "$OUT_DIR" --out-name lab_ide_wasm "$WASM_INPUT"

cat > "$OUT_DIR/README.md" <<'EOF'
# lab-ide-wasm (generated)

This directory is generated by `scripts/build-wasm.sh` from the `lab-ide-wasm`
crate in the sibling `lab` checkout. Do not hand-edit these files — rerun the
script instead, then commit the result.
EOF

SIZE="$(du -h "$OUT_DIR/lab_ide_wasm_bg.wasm" | cut -f1)"
echo "==> done. lab_ide_wasm_bg.wasm is $SIZE"
